language: java
sudo: false

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/de/muehlencord/confluence-rest-client

cache:
  directories:
    - $HOME/.m2/repository
jdk:
  - openjdk8

install: /bin/true

script:
  - mvn package -Dmaven.javadoc.skip=true -V -B
  
after_success: 
